#!/usr/bin/env bash
#
# install.sh — install the LIFX DMX Bridge as a boot service (Raspberry Pi /
# Debian / systemd). After this, the bridge starts automatically on every boot
# — including when the Pi powers back up after an outage — and brings both the
# Art-Net listener and the web UI online in a single process.
#
# Usage:
#   sudo ./install.sh
#
# One process does it all: lifx_web.py serves the web UI AND runs the Art-Net
# listener in-process (it auto-starts the listener on boot once bulbs are
# patched). You do NOT run lifx_control.py separately — a second listener would
# fight the first one for the Art-Net port and universes.
#
set -euo pipefail

SERVICE=lifx-bridge
UNIT="/etc/systemd/system/${SERVICE}.service"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
PYTHON="$(command -v python3 || echo /usr/bin/python3)"

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run with sudo:  sudo ./install.sh" >&2
    exit 1
fi

# --- Pick the config/data directory -----------------------------------------
# The service runs as root (needed for the Network tab's nmcli changes), so its
# config lives in a fixed system path. If you already patched bulbs while
# running by hand, migrate that config so your map/names/password carry over.
DATA_DIR="${LIFX_BRIDGE_DIR:-/var/lib/lifx-bridge}"
mkdir -p "$DATA_DIR"

if [ ! -f "$DATA_DIR/map.json" ]; then
    # Look for an existing ~/.lifx-bridge from manual runs and copy it in.
    for cand in "/root/.lifx-bridge" \
                "$( [ -n "${SUDO_USER:-}" ] && echo "$(getent passwd "$SUDO_USER" | cut -d: -f6)/.lifx-bridge" )"; do
        if [ -n "$cand" ] && [ -f "$cand/map.json" ]; then
            echo "Migrating existing config from $cand -> $DATA_DIR"
            cp -an "$cand/." "$DATA_DIR/" || true
            break
        fi
    done
fi

# --- Write the systemd unit (paths resolved to THIS checkout) ----------------
echo "Writing $UNIT (ExecStart -> $REPO_DIR/lifx_web.py)"
cat > "$UNIT" <<EOF
# Generated by install.sh — re-run the installer to regenerate.
[Unit]
Description=LIFX DMX Bridge (Art-Net listener + web UI)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${PYTHON} ${REPO_DIR}/lifx_web.py
WorkingDirectory=${REPO_DIR}
Environment=LIFX_BRIDGE_DIR=${DATA_DIR}
# Password recovery counts *device reboots*; the window must exceed one Pi boot
# (~20-35s) so three back-to-back power cycles register. Restart=on-failure (not
# always) so a crash loop can't silently trip the reset.
Environment=LIFX_RESTART_WINDOW=60
Environment=LIFX_RESTART_NEEDED=3
Restart=on-failure
RestartSec=3
User=root

[Install]
WantedBy=multi-user.target
EOF

# --- Enable for boot + start now --------------------------------------------
systemctl daemon-reload
systemctl enable --now "$SERVICE"

echo
systemctl --no-pager --full status "$SERVICE" | head -n 12 || true

IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
PORT="$(grep -oE '"web_port":[[:space:]]*[0-9]+' "$REPO_DIR/lifx_web.py" | grep -oE '[0-9]+' | head -1)"
echo
echo "Done. The bridge is enabled and will auto-start on every boot"
echo "(including after a power outage — a Pi powers on by itself when power returns)."
echo "  Web UI:   http://${IP:-<pi-ip>}:${PORT:-8080}"
echo "  Logs:     journalctl -u ${SERVICE} -f"
echo "  Restart:  sudo systemctl restart ${SERVICE}"
